Traceback (most recent call last):
  File "/Users/swathilakhinana/miniconda3/envs/nyc_airbnb_dev/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/swathilakhinana/miniconda3/envs/nyc_airbnb_dev/lib/python3.10/site-packages/wandb/apis/public.py", line 1040, in artifact
    artifact = wandb.Artifact._from_name(
  File "/Users/swathilakhinana/miniconda3/envs/nyc_airbnb_dev/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 256, in _from_name
    raise ValueError(
ValueError: Unable to fetch artifact with name dsri238-s-p-global/nyc_airbnb/trainval_data.csv:latest
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/folders/lv/7pqqcf_s36x401_s8kbz5zz40000gn/T/ipykernel_3498/2999855961.py", line 6, in <module>
    input_path = wandb.use_artifact("trainval_data.csv:latest").file()
  File "/Users/swathilakhinana/miniconda3/envs/nyc_airbnb_dev/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/swathilakhinana/miniconda3/envs/nyc_airbnb_dev/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/swathilakhinana/miniconda3/envs/nyc_airbnb_dev/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2769, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/Users/swathilakhinana/miniconda3/envs/nyc_airbnb_dev/lib/python3.10/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/Users/swathilakhinana/miniconda3/envs/nyc_airbnb_dev/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/swathilakhinana/miniconda3/envs/nyc_airbnb_dev/lib/python3.10/site-packages/wandb/apis/public.py", line 1040, in artifact
    artifact = wandb.Artifact._from_name(
  File "/Users/swathilakhinana/miniconda3/envs/nyc_airbnb_dev/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 256, in _from_name
    raise ValueError(
wandb.errors.CommError: Unable to fetch artifact with name dsri238-s-p-global/nyc_airbnb/trainval_data.csv:latest